### ISSUE TITLE
RPC-JSON getblocktemplate  Out Of Memory

### ISSUE THREAD

**Issue by entaro2k** [News24coin/news24#2]
RPC mining not OK. If method is getblocktemplate RPC call

T 10.10.10.20:39760 -> 10.10.10.41:9994 [AP]
POST / HTTP/1.1.
Host: 10.10.10.41:9994.
Accept-Encoding: deflate, gzip.
Content-Type: application/json.
Content-Length: 52.
Authorization: Basic xxxx
User-Agent: stratum/yiimp.
.

#
T 10.10.10.20:39760 -> 10.10.10.41:9994 [AP]
{"method":"getblocktemplate","params":[{}],"id":"2"}
##
T 10.10.10.41:9994 -> 10.10.10.20:39760 [AP]
HTTP/1.1 500 Internal Server Error.
Date: Thu, 09 Apr 2020 11:22:44 +0000.
Connection: close.
Content-Length: 71.
Content-Type: application/json.
Server: News24-json-rpc/v1.0.0.0-gcbcb549.
.
{"result":null,"error":{"code":-7,"message":"Out of memory"},"id":"2"}

tested News24d - compiled from git source
tested News24d - release
tested News24-Qt - release

all have same problem.

**Comment by News24coin** [comment]
mining is over

**Comment by entaro2k** [comment]
ah ok, at least I know what to do.
